#!/bin/bash
# NOTE: generated by buildgen.py analyzepng.c

CALENDAR_VERSION=$(date '+v%Y_%m_%d')

WINEXE="analyzepng32${CALENDAR_VERSION}.exe"
LINEXE="analyzepng32${CALENDAR_VERSION}.linux"

echo "Building $WINEXE and $LINEXE"
zig cc -s -o "$WINEXE" analyzepng.c -O3 -DCALENDAR_VERSION="\"$CALENDAR_VERSION\"" -target x86-windows-gnu &
zig cc -s -o "$LINEXE" analyzepng.c -O3 -DCALENDAR_VERSION="\"$CALENDAR_VERSION\"" -target x86-linux-musl &
wait

if [ "$1" == "install" ]; then
    echo "installing"
    cp "$WINEXE" /g/mybin/analyzepng.exe
fi
